### ISSUE TITLE
About the problem that the results of the paper cannot be reproduced

### ISSUE THREAD

**Issue by LPH0** [lauramanduchi/DC-GMM#1]
I have done five experiments on MNIST, and the accuracy results on the test set are as follows: 0.895200, 0.893200, 0.959100, 0.953000, 0.961500. The mean is 0.9324 and the standard deviation is 0.03, which is different from the results in the paper. Is there a solution?

**Comment by lauramanduchi** [comment]
Thanks for raising this issue! There was a mismatch with the hyper-parameters (namely batch size). Now it should be fixed and you should be able to reproduce the results of the paper.
